"""Step 2: build the candidate repository table (RUNBOOK 9.4) — measurements only.

Pool (widest option offered at Gate A): repos in a dataset with prebuilt environments
(SWE-bench full, SWE-Gym, SWE-bench-Live full, SWE-rebench filtered, SWE-bench Pro Python)
with at least POOL_MIN eligible tasks under the 1–10 file filter, after removing duplicate
PRs across datasets (G18). Narrower options at Gate A are subsets of this pool.

Measured at a PROVISIONAL snapshot: the base commit of the repo's most recent eligible task.
This is for applying R2/R3 only; D10 pins the real SHAs.

Writes:
  results/step2/dedup_tasks.parquet  task index after G18 deduplication, R1 datasets only
  data/candidates.csv                one row per candidate repo, every rule input and outcome
  logs/candidates_failures.csv       every repo that could not be measured, with the error
"""
from __future__ import annotations

import json
import shutil
import subprocess
import time
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor, as_completed
from pathlib import Path, PurePosixPath

import pandas as pd

from depgraphs.datasets import ROOT
from depgraphs.patches import is_test_path_9_2
from depgraphs.recount import eligible

OUT = ROOT / "results" / "step2"
CLONES = ROOT / "data" / "repos"
R1_DATASETS = ["swebench_full", "swegym", "swebench_live_full", "swerebench_filtered", "swebench_pro"]
POOL_MIN = 10

# Fixed definitions for R2 and the exclusion rules. Written here before measuring.
VENDOR_DIRS = {"vendor", "vendored", "_vendor", "third_party", "thirdparty", "3rdparty",
               "extern", "externals", "external"}
GENERATED_MARKERS = ("generated by", "do not edit", "autogenerated", "auto-generated",
                     "@generated")
# Extensions counted as source code for R2 (programming languages only; no markup/data).
CODE_EXT = {".py", ".pyx", ".pxd", ".pxi", ".pyi", ".c", ".h", ".cc", ".cpp", ".cxx", ".hpp",
            ".hh", ".cu", ".f", ".f90", ".f95", ".for", ".js", ".mjs", ".cjs", ".ts", ".tsx",
            ".jsx", ".go", ".rs", ".java", ".kt", ".scala", ".rb", ".php", ".cs", ".swift",
            ".m", ".mm", ".jl", ".r", ".lua", ".pl", ".sh", ".bash", ".ps1", ".sql", ".vue",
            ".svelte", ".dart", ".zig", ".nim", ".hs", ".ml", ".ex", ".exs", ".erl", ".clj"}
MAX_FILE_BYTES = 2_000_000


def dedup_tasks() -> pd.DataFrame:
    t = pd.read_parquet(OUT / "task_index.parquet")
    t = t[t.dataset.isin(R1_DATASETS)].copy()
    t["task_key"] = t.repo_key + "#" + t.pr_number.fillna(t.base_commit)
    # Keep the first occurrence in R1_DATASETS order (older, more established datasets first).
    t["_order"] = t.dataset.map({d: i for i, d in enumerate(R1_DATASETS)})
    t = t.sort_values(["_order", "instance_id"])
    dup_sources = t.groupby("task_key").dataset.agg(lambda s: ";".join(sorted(set(s))))
    t = t.drop_duplicates("task_key").drop(columns="_order")
    t["also_in"] = t.task_key.map(dup_sources)
    t.to_parquet(OUT / "dedup_tasks.parquet", index=False)
    return t


def _git(args, cwd, timeout=900):
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True,
                          timeout=timeout, check=True)


def _commit_date(repo_dir: Path, sha: str) -> int:
    return int(_git(["show", "-s", "--format=%ct", sha], repo_dir).stdout.strip())


def fetch_snapshot(repo: str, shas: list[str]) -> tuple[Path, str, float]:
    """Shallow-fetch the candidate commits and check out the newest. Returns dir, sha, seconds."""
    d = CLONES / repo.replace("/", "__")
    t0 = time.time()
    if not (d / ".git").exists():
        d.mkdir(parents=True, exist_ok=True)
        _git(["init", "-q"], d)
        _git(["remote", "add", "origin", f"https://github.com/{repo}.git"], d)
        _git(["config", "core.longpaths", "true"], d)
    _git(["fetch", "-q", "--depth", "1", "origin", *shas], d)
    sha = max(shas, key=lambda s: _commit_date(d, s)) if len(shas) > 1 else shas[0]
    _git(["-c", "advice.detachedHead=false", "checkout", "-q", "-f", sha], d)
    return d, sha, time.time() - t0


def _analyse(args):
    import pygount
    path, rel = args
    try:
        a = pygount.SourceAnalysis.from_file(path, "g", encoding="automatic")
        return rel, a.code_count, a.language
    except Exception as e:  # counted, not dropped
        return rel, None, f"ERROR:{type(e).__name__}"


def measure(repo_dir: Path, pool: ProcessPoolExecutor) -> dict:
    files = [p for p in repo_dir.rglob("*") if p.is_file() and ".git" not in p.parts]
    rel = {p: PurePosixPath(p.relative_to(repo_dir).as_posix()) for p in files}
    is_test = {p: is_test_path_9_2(str(rel[p])) for p in files}
    is_vendor = {p: any(x in VENDOR_DIRS for x in rel[p].parts[:-1]) for p in files}

    py = [p for p in files if p.suffix == ".py"]
    src_py = [p for p in py if not is_test[p] and not is_vendor[p]]
    code = [p for p in files if p.suffix.lower() in CODE_EXT and not is_test[p]
            and p.stat().st_size <= MAX_FILE_BYTES]
    results = dict((r, (n, lang)) for r, n, lang in
                   pool.map(_analyse, [(str(p), str(rel[p])) for p in code], chunksize=32))

    def lines(ps):
        return sum((results.get(str(rel[p]), (0, ""))[0] or 0) for p in ps)

    code_nonvendor = [p for p in code if not is_vendor[p]]
    py_nonvendor = [p for p in code_nonvendor if p.suffix == ".py"]
    generated = []
    for p in code_nonvendor:
        try:
            with open(p, encoding="utf-8", errors="ignore") as fh:
                head = "".join(fh.readline() for _ in range(5)).lower()
            if any(m in head for m in GENERATED_MARKERS):
                generated.append(p)
        except OSError:
            pass
    total_code = lines(code)
    lic = sorted(str(rel[p]) for p in files if len(rel[p].parts) == 1
                 and rel[p].name.upper().startswith(("LICENSE", "LICENCE", "COPYING")))
    packaging = [str(rel[p]) for p in files if rel[p].name in ("setup.py", "pyproject.toml")
                 and not is_test[p] and not is_vendor[p]]
    return {
        "files_total": len(files),
        "py_files": len(py),
        "nontest_py_files": len(src_py),                       # R3 input
        "test_py_files": sum(is_test[p] for p in py),
        "code_lines_nontest_nonvendor": lines(code_nonvendor),
        "py_lines_nontest_nonvendor": lines(py_nonvendor),
        "python_share": round(lines(py_nonvendor) / max(lines(code_nonvendor), 1), 4),  # R2
        "vendored_code_lines": lines([p for p in code if is_vendor[p]]),
        "generated_code_lines": lines(generated),
        "generated_or_vendored_share": round(
            (lines([p for p in code if is_vendor[p]]) + lines(generated)) / max(total_code, 1), 4),
        "ipynb_files": sum(p.suffix == ".ipynb" for p in files),
        "packaging_files": len(packaging),
        "packaging_paths": ";".join(sorted(packaging)[:10]),
        "licence_files": ";".join(lic),
        "count_errors": sum(1 for v in results.values() if v[0] is None),
        "checkout_mb": round(sum(p.stat().st_size for p in files) / 1e6, 1),
    }


def main(workers: int = 6):
    t = dedup_tasks()
    e1 = eligible(t, 1)
    e2 = eligible(t, 2)
    per = pd.DataFrame({
        "eligible_1_10": t[e1].groupby("repo_key").size(),
        "eligible_2_10": t[e2].groupby("repo_key").size(),
    }).fillna(0).astype(int)
    pool = per[per.eligible_1_10 >= POOL_MIN].sort_index()
    info = t.groupby("repo_key").agg(
        repo=("repo", "first"),
        datasets=("dataset", lambda s: ";".join(sorted(set(s)))),
        tasks_all=("task_key", "size"),
        date_min=("created_at", "min"), date_max=("created_at", "max"),
        licence_dataset=("licence", lambda s: s.dropna().iloc[0] if s.notna().any() else None))
    cand = pool.join(info)

    # Provisional snapshot candidates: newest eligible task by date; Pro has no dates,
    # so fetch all its eligible base commits and take the newest by commit date.
    snap = {}
    for rk, d in t[e1 & t.repo_key.isin(cand.index)].groupby("repo_key"):
        if d.created_at.notna().all():
            snap[rk] = [d.sort_values("created_at").base_commit.iloc[-1]]
        else:
            snap[rk] = sorted(set(d.base_commit))

    out_csv = ROOT / "data" / "candidates.csv"
    cache = ROOT / "data" / "candidates_measure.jsonl"
    done = {}
    if cache.exists():
        for line in cache.read_text().splitlines():
            r = json.loads(line)
            done[r["repo_key"]] = r
    failures = []
    todo = [rk for rk in cand.index if rk not in done]
    with ProcessPoolExecutor(8) as cpool, ThreadPoolExecutor(workers) as tpool:
        futs = {tpool.submit(fetch_snapshot, cand.loc[rk, "repo"], snap[rk]): rk for rk in todo}
        for i, f in enumerate(as_completed(futs), 1):
            rk = futs[f]
            try:
                d, sha, secs = f.result()
                t0 = time.time()
                m = measure(d, cpool)
                r = {"repo_key": rk, "provisional_sha": sha, "fetch_seconds": round(secs, 1),
                     "measure_seconds": round(time.time() - t0, 1), **m}
                done[rk] = r
                with open(cache, "a") as fh:
                    fh.write(json.dumps(r) + "\n")
            except Exception as e:
                failures.append({"repo_key": rk, "error": f"{type(e).__name__}: "
                                 f"{getattr(e, 'stderr', '') or e}"[:500]})
            (ROOT / "logs" / "progress.json").write_text(json.dumps(
                {"stage": "candidates", "done": i, "total": len(todo), "failed": len(failures)}))
    pd.DataFrame(failures, columns=["repo_key", "error"]).to_csv(
        ROOT / "logs" / "candidates_failures.csv", index=False)
    m = pd.DataFrame(list(done.values())).set_index("repo_key") if done else pd.DataFrame()
    cand.join(m).to_csv(out_csv)


if __name__ == "__main__":
    main()
